### ISSUE TITLE
저 개쓰레기 챗에서 벗어나고 싶다 프로젝트 인데 이슈에다 만듬

### ISSUE THREAD

**Issue by onetwopunchhook** [onetwopunchhook/pub#1]
그 챗에게 하는 말

백업 힘들어서 애들 개 고생 시켜 등등
이유를 쓰는 시간도 아깝다..

하지만 한편으로는 고마워. 너 없었으면 시작도 못했어.

fan이 도와주고 있음

**Comment by onetwopunchhook** [comment]
fan이 무슨 리플라식으로 다만들었다고 하면 됨

**Comment by onetwopunchhook** [comment]
여기는 현재 퍼블릭하기 때문에, 특정 단어 조심해서 써야 해

**Comment by unodos34** [comment]
ok 확인

**Comment by onetwopunchhook** [comment]
이건 사실 계정 두개 만드는거, 원래가 프로젝트여서... 나중에 설명할께. 여하튼 이건 계정 두개 만든걸로 너꺼 하나 만들거로 완수라고 치고. 닫을께.
